# ===============================================================
# CORE APPLICATION
# ===============================================================
server.port=8081
spring.application.name=user-service
spring.output.ansi.enabled=ALWAYS
spring.main.banner-mode=off
spring.threads.virtual.enabled=true

# ===============================================================
# EUREKA SERVER
# ===============================================================
eureka.client.enabled=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================================================
# INFRASTRUCTURE & DATA
# ===============================================================
## SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/keycloak
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
## Kafka
spring.kafka.topic.user-registration=user-registration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
### Keycloak
keycloak.server-url=http://localhost:9000
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.user-name=admin
keycloak.admin.password=admin
keycloak.current-realm=graduation-thesis
keycloak.client-id=graduation-thesis-id

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server-url}/realms/${keycloak.current-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.server-url}/realms/${keycloak.current-realm}/protocol/openid-connect/certs
